### ISSUE TITLE
Issue when stretching to SVG

### ISSUE THREAD

**Issue by KoolAidKid** [JarrettR/Stretch#1]
![image](https://user-images.githubusercontent.com/17104293/93753438-2624c480-fbce-11ea-85ec-ca86e6521564.png)
I believe this has something to do with missing plugins,but I could be wrong.

**Comment by JarrettR** [comment]
Hey,

That's an issue with parsing the kicad PCB file. It just means that there's an edge-case in there that I haven't seen before.

If you can post that file, I can take a look at it at some point!

**Comment by KoolAidKid** [comment]
Sure! what’s the best way to get you access ? just post it on github and
link?

**Comment by JarrettR** [comment]
I think you can save it as pcb.kicad_pcb.txt and just attach it to this issue.

**Comment by KoolAidKid** [comment]
Does this work?

[pcb.zip](https://github.com/JarrettR/Stretch/files/5258560/pcb.zip)

**Comment by JarrettR** [comment]
That only has the .pro file, I just need the .kicad_pcb file

**Comment by KoolAidKid** [comment]
[pcb (2).zip](https://github.com/JarrettR/Stretch/files/5259253/pcb.2.zip)
Oops!

**Comment by JarrettR** [comment]
Fixed with https://github.com/JarrettR/Stretch/commit/ad1907ec0f83adfb4c3b62894ecca6ac964a133a
