### ISSUE TITLE
Not able to see plugin icons

### ISSUE THREAD

**Issue by thoonky** [JarrettR/Stretch#10]
Copied the contents of Stretch-master to my plugins folder
C:\Program Files\KiCad\share\kicad\scripting\plugins
however, I am not able to load the plugins (refresh does not see anynew items).
Care to provide a sample?

**Comment by JarrettR** [comment]
Rename the folder to `Stretch` ?

Just checked on 5.1.10 on Linux (previously untested setup) and it seems to work
