### ISSUE TITLE
Windows depedency installation error

### ISSUE THREAD

**Issue by sujitth** [JarrettR/Stretch#2]
I was trying to install the dependency bs4 as mentioned in the instruction which gives an exception error as attached in the picture.

![image](https://user-images.githubusercontent.com/6084883/95577401-b4fb6300-0a4f-11eb-94f3-de901ee29e78.png)

Can I install from the Cmd prompt(Python 3.8.5) like "pip install bs4"  instead of  "<Path>\KiCad\bin\python.exe -m pip install bs4 " ?
What is the difference?

**Comment by JarrettR** [comment]
The latter command uses the portable version of Python that KiCad requires. It is 2.7 due to internal dependencies in KiCad, which is annoying, but I don't think that's the issue.

Can you try again, but with the command prompt opened with administrator privileges?

**Comment by designer2k2** [comment]
got here the same initially, but with adminstrator privileges it worked!
