### ISSUE TITLE
`soupsieve` package is not installed

### ISSUE THREAD

**Issue by ONLYA** [JarrettR/Stretch#30]
When I installed and refresh this plugin, it shows "The soupsieve package is not installed. CSS selectors cannot be used."

I solved this issue by installing the required package to the KiCad python. However, is it possible to install all the required packages during the initialisation or installation stage?

**Comment by ponzifex** [comment]
So, I have installed soupsieve like:
C:\Program Files\KiCad\8.0\bin\python.exe -m pip install soupsieve
Then, KiCad needs to be restarted to install Stretch.

**Comment by JarrettR** [comment]
This has been "solved" by removing the internal beautifulsoup package and putting the responsibility on the user to install it.

`C:\Program Files\KiCad\8.0\bin\python.exe -m pip install beautifulsoup4` should do it

**Comment by ONLYA** [comment]
I mean, in perspective of user-friendliness, is it possible to automatically install the required package? For example, you can use the `pip` module to install it. The fallback of the `install` function to ensure it would work on all python versions. Even though it is not recommended, it is a good cross-platform solution. (I use Ubuntu instead of Windows)

**Comment by JarrettR** [comment]
No, KiCad doesn't support automatically installing python module dependencies. I was trying to get around that by bundling BS4, but there are additional problems, due to how KiCad handles paths inside plugins.

Ideally, the KiCad PCM eventually supports dependency handling, and then this can be revisited.
