### ISSUE TITLE
Kicad 8.0 support

### ISSUE THREAD

**Issue by ponzifex** [JarrettR/Stretch#34]
Hi,

I'm using the Stretch plugin that can be installed through KiCad's plugin manager.
Importing back even the unmodified SVG int KiCad 8.0 gives me the following error:

![image](https://github.com/JarrettR/Stretch/assets/6368578/15a5d74c-2302-4632-8956-123b7a159b50)

Original pcb file:
[kicad_test.kicad_pcb.txt](https://github.com/JarrettR/Stretch/files/14612217/kicad_test.kicad_pcb.txt)

Stretch converted SVG to pcb:
[kicad_test.kicad_pcb_imported.txt](https://github.com/JarrettR/Stretch/files/14612243/kicad_test.kicad_pcb_imported.txt)

Looks like the problem is with this line:
(generator_version 8.0)
The version number should be in quotes like
(generator_version "8.0")

**Comment by JarrettR** [comment]
Thanks for the report!
