### ISSUE TITLE
Text severely messed up on export

### ISSUE THREAD

**Issue by holmesrichards** [JarrettR/Stretch#7]
Using:
Inkscape 1.0.2 (1.0.2+r75+1)
KiCad Version: 5.1.10-88a1d61d58~88~ubuntu20.04.1, release build
```
Libraries:
    wxWidgets 3.0.4
    libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Platform: Linux 5.4.0-72-generic x86_64, 64 bit, Little endian, wxGTK
Build Info:
    wxWidgets: 3.0.4 (wchar_t,wx containers,compatible with 2.8) GTK+ 3.24
    Boost: 1.71.0
    OpenCASCADE Community Edition: 6.9.1
    Curl: 7.68.0
    Compiler: GCC 9.3.0 with C++ ABI 1013

Build settings:
    USE_WX_GRAPHICS_CONTEXT=OFF
    USE_WX_OVERLAY=ON
    KICAD_SCRIPTING=ON
    KICAD_SCRIPTING_MODULES=ON
    KICAD_SCRIPTING_PYTHON3=ON
    KICAD_SCRIPTING_WXPYTHON=ON
    KICAD_SCRIPTING_WXPYTHON_PHOENIX=ON
    KICAD_SCRIPTING_ACTION_MENU=ON
    BUILD_GITHUB_PLUGIN=ON
    KICAD_USE_OCE=ON
    KICAD_USE_OCC=OFF
    KICAD_SPICE=ON

```
Linux Mint 20.1
Stretch latest

I tried Stretch export on a sandbox example and it badly messes up text on output. Font sizes are wrong, at least one text object is moved, and a bunch are gone entirely. And several %R references are unresolved.

KiCad original:
![kicad_sandbox_orig](https://user-images.githubusercontent.com/56895621/116822939-9970ba80-ab4f-11eb-912b-1ab5031d0003.png)

Stretch export:
![stretch_sandbox_export](https://user-images.githubusercontent.com/56895621/116822948-a2618c00-ab4f-11eb-899a-bce1eabd6506.png)

**Comment by Sonosus** [comment]
@analogoutput have you tried importing it back into KiCAD. I have the same problem but the text goes back to its original state when I reimport. From the readme: Fonts are iffy, and dimensions may be a little off. This imports properly back into the PCB if untouched, however.

**Comment by holmesrichards** [comment]
I hadn't. Yes, it does import back into KiCad correctly. I do think this issue isn't well described by "fonts are iffy", though; it's a lot worse than that. But thanks for the clarification.

**Comment by holmesrichards** [comment]
It's not just text. I created a polygon, an arc, and a circle in the F.Silk layer in PCBnew. On export to Inkscape the polygon and arc were there but the circle had disappeared. On re-import to PCBnew the circle was there.

In PCBnew:
![kicadorig1](https://user-images.githubusercontent.com/56895621/116940329-d023ff00-ac3b-11eb-9cde-c475f088d4b9.png)

In Inkscape:
![inkscapeimport2](https://user-images.githubusercontent.com/56895621/116940349-d6b27680-ac3b-11eb-8b9b-31e4dbe57478.png)

**Comment by JarrettR** [comment]
Proper font rendering in Inkscape is a challenging issue. I don't think it'll ever get fully solved in this tool, or similar. There are two issues at play: KiCad's font is unavailable in Inkscape, and KiCad also has independent width/height/stroke values that control how the text is rendered, which isn't really done in any other tool. Perhaps a workaround I could do is to instead draw the text as a vector line, and then vary the stroke width appropriately. It's worth adding to the feature list.

Not rendering designators is appropriate, I feel.  As we've already determined, the extent of text modifications you can reliably do in your vector software is repositioning and rotation, and maybe resizing. If you actually want to do some fun artsy stuff with it, you need to instead convert the text to polygons, so it's easy enough to rename the designator to whatever you like at that time. But current functionality will allow you to bring the PCB back into KiCad and not lose your reference information, which is one of the main goals of this project.

Looks like rotation inside modules is messed up in your original screenshots, too, which is something I do remember having issues with. I think I handled it better in the refactor branch (which is not usable yet, unfortunately).

Circle disappearing is another issue. It's possible that support for circles was never completed, I don't remember - It's slightly weird that KiCad treats arcs and circles differently.

**Comment by JarrettR** [comment]
Won't fix, I feel this is adequately described in the readme, submit a PR with exposition if necessary
